// flow-typed signature: 04248ffee84620485f55866d0aec863a
// flow-typed version: <<STUB>>/eslint-plugin-no-async-without-await_v~1.2.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-no-async-without-await'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-no-async-without-await' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-no-async-without-await/no-async-without-await' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-no-async-without-await/index' {
  declare module.exports: $Exports<'eslint-plugin-no-async-without-await'>;
}
declare module 'eslint-plugin-no-async-without-await/index.js' {
  declare module.exports: $Exports<'eslint-plugin-no-async-without-await'>;
}
declare module 'eslint-plugin-no-async-without-await/no-async-without-await.js' {
  declare module.exports: $Exports<'eslint-plugin-no-async-without-await/no-async-without-await'>;
}
