// flow-typed signature: 9292f72ede2f840dbe7e0abe75bf7803
// flow-typed version: <<STUB>>/range_v^0.0.3/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'range'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'range' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'range/lib/range' {
  declare module.exports: any;
}

// Filename aliases
declare module 'range/lib/range.js' {
  declare module.exports: $Exports<'range/lib/range'>;
}
