export const MOUSE_DOWN = 'game/MOUSE_DOWN'
export const MOUSE_MOVE = 'game/MOUSE_MOVE'
export const MOUSE_UP = 'game/MOUSE_UP'
export const SCROLL = 'game/SCROLL'
export const CELL_SELECTED = 'game/CELL_SELECTED'
