export const MOUSE_DOWN = 'game/MOUSE_DOWN'
export const MOUSE_MOVE = 'game/MOUSE_MOVE'
export const MOUSE_UP = 'game/MOUSE_UP'
export const SCROLL = 'game/SCROLL'
export const CELL_SELECTED = 'game/CELL_SELECTED'
export const MOVE_SELECTED_CELL = 'game/MOVE_SELECTED_CELL'
export const CLEAR_MOVES = 'game/CLEAR_MOVES'
export const START_GAME = 'game/START_GAME'
